# Generated by Django 5.2.3 on 2025-06-25 12:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import nurse_calling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nurse_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.bed')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.hospital')),
                ('building_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_manager', to='nurse_calling.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hospital', to='nurse_calling.nurse'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.building')),
                ('floor_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_manager', to='nurse_calling.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('call_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.bed')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.device')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurse_calling.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='nurses',
            field=models.ManyToManyField(related_name='assigned_beds', to='nurse_calling.nurse'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='nurse_calling.bed')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.staffteam'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('nurse', 'Nurse')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='nurse_users', related_query_name='nurse_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='nurse_users_permissions', related_query_name='nurse_user_permission', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.floor')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.CharField(default=nurse_calling.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.floor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.staffteam')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.ward')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.ward'),
        ),
    ]
